//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagerApp.ReportServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportServiceReference.IReportService")]
    public interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ShowAllAlarmsInTimePeriod", ReplyAction="http://tempuri.org/IReportService/ShowAllAlarmsInTimePeriodResponse")]
        string ShowAllAlarmsInTimePeriod(System.DateTime startTime, System.DateTime endTime, bool sortByPriority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ShowAllAlarmsInTimePeriod", ReplyAction="http://tempuri.org/IReportService/ShowAllAlarmsInTimePeriodResponse")]
        System.Threading.Tasks.Task<string> ShowAllAlarmsInTimePeriodAsync(System.DateTime startTime, System.DateTime endTime, bool sortByPriority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ShowAlarmsByPriority", ReplyAction="http://tempuri.org/IReportService/ShowAlarmsByPriorityResponse")]
        string ShowAlarmsByPriority(int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ShowAlarmsByPriority", ReplyAction="http://tempuri.org/IReportService/ShowAlarmsByPriorityResponse")]
        System.Threading.Tasks.Task<string> ShowAlarmsByPriorityAsync(int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ShowTagValuesInTimePeriod", ReplyAction="http://tempuri.org/IReportService/ShowTagValuesInTimePeriodResponse")]
        string ShowTagValuesInTimePeriod(System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ShowTagValuesInTimePeriod", ReplyAction="http://tempuri.org/IReportService/ShowTagValuesInTimePeriodResponse")]
        System.Threading.Tasks.Task<string> ShowTagValuesInTimePeriodAsync(System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ShowLastValuesOfAITags", ReplyAction="http://tempuri.org/IReportService/ShowLastValuesOfAITagsResponse")]
        string ShowLastValuesOfAITags();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ShowLastValuesOfAITags", ReplyAction="http://tempuri.org/IReportService/ShowLastValuesOfAITagsResponse")]
        System.Threading.Tasks.Task<string> ShowLastValuesOfAITagsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ShowLastValuesOfDITags", ReplyAction="http://tempuri.org/IReportService/ShowLastValuesOfDITagsResponse")]
        string ShowLastValuesOfDITags();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ShowLastValuesOfDITags", ReplyAction="http://tempuri.org/IReportService/ShowLastValuesOfDITagsResponse")]
        System.Threading.Tasks.Task<string> ShowLastValuesOfDITagsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ShowValuesOfTagById", ReplyAction="http://tempuri.org/IReportService/ShowValuesOfTagByIdResponse")]
        string ShowValuesOfTagById(string tagId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ShowValuesOfTagById", ReplyAction="http://tempuri.org/IReportService/ShowValuesOfTagByIdResponse")]
        System.Threading.Tasks.Task<string> ShowValuesOfTagByIdAsync(string tagId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportServiceChannel : ReportManagerApp.ReportServiceReference.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<ReportManagerApp.ReportServiceReference.IReportService>, ReportManagerApp.ReportServiceReference.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ShowAllAlarmsInTimePeriod(System.DateTime startTime, System.DateTime endTime, bool sortByPriority) {
            return base.Channel.ShowAllAlarmsInTimePeriod(startTime, endTime, sortByPriority);
        }
        
        public System.Threading.Tasks.Task<string> ShowAllAlarmsInTimePeriodAsync(System.DateTime startTime, System.DateTime endTime, bool sortByPriority) {
            return base.Channel.ShowAllAlarmsInTimePeriodAsync(startTime, endTime, sortByPriority);
        }
        
        public string ShowAlarmsByPriority(int priority) {
            return base.Channel.ShowAlarmsByPriority(priority);
        }
        
        public System.Threading.Tasks.Task<string> ShowAlarmsByPriorityAsync(int priority) {
            return base.Channel.ShowAlarmsByPriorityAsync(priority);
        }
        
        public string ShowTagValuesInTimePeriod(System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.ShowTagValuesInTimePeriod(startTime, endTime);
        }
        
        public System.Threading.Tasks.Task<string> ShowTagValuesInTimePeriodAsync(System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.ShowTagValuesInTimePeriodAsync(startTime, endTime);
        }
        
        public string ShowLastValuesOfAITags() {
            return base.Channel.ShowLastValuesOfAITags();
        }
        
        public System.Threading.Tasks.Task<string> ShowLastValuesOfAITagsAsync() {
            return base.Channel.ShowLastValuesOfAITagsAsync();
        }
        
        public string ShowLastValuesOfDITags() {
            return base.Channel.ShowLastValuesOfDITags();
        }
        
        public System.Threading.Tasks.Task<string> ShowLastValuesOfDITagsAsync() {
            return base.Channel.ShowLastValuesOfDITagsAsync();
        }
        
        public string ShowValuesOfTagById(string tagId) {
            return base.Channel.ShowValuesOfTagById(tagId);
        }
        
        public System.Threading.Tasks.Task<string> ShowValuesOfTagByIdAsync(string tagId) {
            return base.Channel.ShowValuesOfTagByIdAsync(tagId);
        }
    }
}
